theme: jekyll-theme-cayman
title: Welcome to thomasricks655’s homepage
description: That's not my real name but this is just for school ahaha but maybe I'll actually use GitHub pages someday cuz it's cool.
